### ISSUE TITLE
Unresolvable dependency resolving [Parameter #0 [ $app ]] in class Illuminate\Database\DatabaseManager

### ISSUE THREAD

**Issue by felixmpa** [Crinsane/LaravelShoppingcart#387]
It error is using octobercms.

Unresolvable dependency resolving [Parameter #0 [ $app ]] in class Illuminate\Database\DatabaseManager

I installed -composer require:

gloudemans/shoppingcart#dev-dev-laravel55

I setup a plugin with:

 public function boot()
    {
        App::register('\Gloudemans\Shoppingcart\ShoppingcartServiceProvider');

        $alias = AliasLoader::getInstance();

        $alias->alias('Cart', 'Gloudemans\Shoppingcart\Facades\Cart');

    }
This is working well on my localhost running on Windows. But now on ubuntu on DigitalOcean I track the error on:

\\vendor\Gloudemans\shoppincart\src\Cart.php when the follow function is called.

private function getConnection()
{
    $connectionName = $this->getConnectionName();

    return app(DatabaseManager::class)->connection($connectionName);
}
This part "app(DatabaseManager::class)" show the error.

I was looking information about bindings and give all sub-folder permission but the error persists.

**Comment by pmhou** [comment]
Just pulled down this package and had the same issue, albeit using it with OctoberCMS rather than plain Laravel.

It seems the DatabaseManager is resolved with the 'db' alias normally. I got around this by registering the database manager using the FQN and returning the db instance from the container.

```php
$this->app->singleton(DatabaseManager::class, function ($app) {
    return $app->make('db');
});
```

Hope this helps anyone else with this issue!

**Comment by SebastiaanKloos** [comment]
@pmhou Thank you for solving this problem. I've had the same issue with OctoberCMS!

**Comment by chrisvidal** [comment]
Having the same issue with OctoberCMS.

Where do you put this code @SebastiaanKloos ?

I tried to insert it into the `register()` or `boot()` method in the plugin.php code but it does not solve the exception

thanks

EDIT: OK it works, i was missing the 'use' keyword for the databasemanager class
