### ISSUE TITLE
Cart 'options' => returns an empty array

### ISSUE THREAD

**Issue by Mr3agle** [Crinsane/LaravelShoppingcart#553]
When passing ['size' => 'someSize'] as fifth argument in Cart::add() function it doesn't use it and return an empty array. How can i fix this?

**Comment by giuliogatto** [comment]
This has been fixed here: 
https://github.com/bumbummen99/LaravelShoppingcart/commit/279e820760e8ccaf1a3b1a7ffe6f48b7083d243d

**Comment by bumbummen99** [comment]
To be honest I think I have Just fixed my own mistake from manually merging weight there as I had Updated the method Signature in the CartItem class but not in Cart to include weight.

**Comment by giuliogatto** [comment]
@bumbummen99 thank you, did you update the packagist repo? As of yesterday the commit wasn't included when installing through Composer. Hence the bug was still present

**Comment by bumbummen99** [comment]
@giuliogatto you are right, this change has not been tagged or synced to packagist by me until now. It should now be available as 2.8.1.

**Comment by giuliogatto** [comment]
@bumbummen99 thank you for the reply.
Have you already synced? If I do:  'composer require bumbummen99/shoppingcart' I get 2.8.1 but still the old versions of the code with the bug in Cart.php functions add() and createCartItem()

**Comment by bumbummen99** [comment]
@giuliogatto It should have synced, it has been showing up on the [packagist page](https://packagist.org/packages/bumbummen99/shoppingcart) for me on my end since. Just synced it again but it should have already been synced.

**Comment by giuliogatto** [comment]
That's very strange.. I am still getting 2.8 and the bug in the code. (please see screenshot)
Could you confirm that it's only my local problem and you can require the last version without any problem?

![composer](https://user-images.githubusercontent.com/11378447/57290672-28ac7a00-70be-11e9-8271-3c24b1d6556a.PNG)

**Comment by bumbummen99** [comment]
@giuliogatto You are right, i have managed to set the tag right before the merge :sweat_smile: I have corrected it to the right commit. If composer will not notice that you'll maybe have to re-require it or just remove the vendor folder and run composer install. Thanks for mentioning it and sorry for the inconveniance.
